# Generated by Django 3.2 on 2022-12-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_review_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_read',
            field=models.DateField(null=True),
        ),
    ]
